import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth, signIn, signOut } from "@/auth";
import { Space_Grotesk } from "next/font/google";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function handleSignIn() {
  "use server";
  await signIn("google");
}

async function handleSignOut() {
  "use server";
  await signOut();
}

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await auth();
  return (
    <html
      lang="pt-br"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        {session ? (
          <div>
            {" "}
            <span>Olá, {session.user?.name}</span>{" "}
            <form action={handleSignOut}>
              {" "}
              <button type="submit">Sair</button>{" "}
            </form>{" "}
          </div>
        ) : (
          <form action={handleSignIn}>
            {" "}
            <button type="submit">Entrar com Google</button>{" "}
          </form>
        )}
        {children}
      </body>
    </html>
  );
}
